# Generated by Django 2.2 on 2021-11-22 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_pro", models.BooleanField(default=False)),
                ("pro_expiry_date", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[("F", "FREE"), ("M", "MONTHLY"), ("Y", "YEARLY")],
                        default="FREE",
                        max_length=100,
                    ),
                ),
                ("sub_id", models.CharField(max_length=100)),
                ("customer_id", models.CharField(max_length=100)),
                ("charge_id", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
